version: "3"

services:
  client:
    container_name: client
    image: react:dev
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client/src:/usr/src/app/src
    depends_on:
      - server
  server:
    container_name: server
    image: nodejs:dev
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    stdin_open: true
    volumes:
      - ./server/db:/usr/src/app/db
      - ./server/routes:/usr/src/app/routes
#    depends_on:
#      - mongo
#  mongo:
#    container_name: database
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/